### ISSUE TITLE
TagsManifest in documentation

### ISSUE THREAD

**Issue by MauriceArikoglu** [caching-tools/next-shared-cache#181]
In the documentation, the following is stated

> Furthermore, to ensure on-demand revalidation is performed correctly, a common TagsManifest for all pods must be present. Since the original class checks the TagsManifest, it is necessary to maintain this functionality.

This is unclear to me - it sounds like a custom config is required but there is no further detail in the documentation. Can you clarify?

Lbnl: Thanks for the package!

**Comment by better-salmon** [comment]
Hey @MauriceArikoglu! Sure, I will add a more detailed explanation on this. But first, I need to fix backward compatibility with older versions of Next.js. Keep track of the issue you've created. I don't think it will take long.

**Comment by MauriceArikoglu** [comment]
@better-salmon thanks. Let me know if I can help with something.

To answer the original question: am I right that the library handles the creation of TagManifest? No action needed?

**Comment by better-salmon** [comment]
If you are using [Redis stack Handler](https://caching-tools.github.io/next-shared-cache/redis-stack) you got covered by the Handler. If you are making something custom you need to set common TagsManifest in your cache store. Check out [this example](https://caching-tools.github.io/next-shared-cache/redis-stack-custom). The following code sets common TagsManifest in Redis:

```js
await client.json.set(TAGS_MANIFEST_KEY, '.', localTagsManifest, {
    NX: true,
});
```

If you check [Redis strings](https://caching-tools.github.io/next-shared-cache/redis-strings-custom) example you will see different approach. Due to simple nature of Redis String and Hash data types there is no need to set common manifest as a JSON data structure. And you will need to assemble TagsManifest from Hash table like in the following code:

```js
async getTagsManifest() {
    try {
        const remoteTagsManifest = await client.hGetAll(TAGS_MANIFEST_KEY);

        if (!remoteTagsManifest) {
            return localTagsManifest;
        }

        Object.entries(remoteTagsManifest).reduce((acc, [tag, revalidatedAt]) => {
            acc[tag] = { revalidatedAt: parseInt(revalidatedAt ?? '0', 10) };
            return acc;
        }, localTagsManifest.items);

        return localTagsManifest;
    } catch (error) {
        return localTagsManifest;
    }
}
```

**Comment by better-salmon** [comment]
Hello, @MauriceArikoglu! Please take a look at the new documentation in PR #198. I wanted to draw your attention to the updated version of TagsManifest in [the docs](https://github.com/caching-tools/next-shared-cache/pull/198/files#diff-87fdfc38b2985b175c9456b22ae0d33063587e5bbbe514550d66a224f1f626aa).

**Comment by MauriceArikoglu** [comment]
> Hello, @MauriceArikoglu! Please take a look at the new documentation in PR #198. I wanted to draw your attention to the updated version of TagsManifest in [the docs](https://github.com/caching-tools/next-shared-cache/pull/198/files#diff-87fdfc38b2985b175c9456b22ae0d33063587e5bbbe514550d66a224f1f626aa).

Hi @better-salmon ive left a PR comment :)
