### ISSUE TITLE
404 page status is not updated from the moment the page is cached.

### ISSUE THREAD

**Issue by zecka** [caching-tools/next-shared-cache#565]
**Brief Description of the Bug**
When a 404 page is cached the status of page never change event if page component doesn't return notFound() anymore.

Note that I got the same issue with native nextjs cache and already open en issue on nextjs repo: https://github.com/vercel/next.js/issues/66540

Feel free to close this issue if it should not be addresed by neshca/cache-handler 

**Severity**
[Major]

**Frequency of Occurrence**
[Always]

**Steps to Reproduce**

1.  clone repository on branch neshca/cache-handler 
https://github.com/zeckaissue/nextjs-cache-404-status-update/tree/neshca/cache-handler
2. `npm install`
3. `npm run demo`
4.  Go to: http://localhost:3000/hello-2
5. edit demo/articles.json and modifiy slug from hello to hello-2
6. Refresh http://localhost:3000/hello-2 until “Hello world” appears
7. Chek network tab and http://localhost:3000/hello-2 still with a 404 status
**Expected vs. Actual Behavior**
Describe what you expected to happen and what actually happened.

**Screenshots/Logs**
https://github.com/vercel/next.js/assets/18116930/ec939bec-3df7-40b4-b609-e5aed9d4e6ef

**Environment:**

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

**Dependencies and Versions**
  "@neshca/cache-handler": "^1.3.2",

**Comment by better-salmon** [comment]
Hello @zecka! This issue is not related to `@neshca/cache-handler`. While this behavior is acceptable when using native cache, it's problematic for shared cache setups. If multiple pages display a 404 error, Next.js will store the same 404 page in the cache numerous times. However, there's a potential solution. Since these pages are identical, it might be beneficial to have a single cached 404 page linked to any page needing to display a 404 error. This approach can save space in the cache store and potentially improve performance. Or we should not cache 404 and rely on Next.js to render it every time. Thank you for pointing out the issue with 404 caching.

I'm closing this issue and beginning work on an optimization.

**Comment by zecka** [comment]
@better-salmon  I'm not sure I understand you...
How could we share a cache for a 404 page, knowing that the cache key of a page is its path. At the time of the get cache method, we don't yet know whether the page is a 404 or not (in the case of a dynamic path, such as the detail page of a blog post). What's more, a page that was previously a 404 may later become a 200, which is the main point I'm making here.
