### ISSUE TITLE
Redis cluster mode enabled - CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by Jon1VK** [caching-tools/next-shared-cache#626]
**Brief Description of the Bug**
When Redis cluster mode is enabled, the redis-strings handlers revalidateTag function does not work properly and throws an error "CROSSSLOT Keys in request don't hash to the same slot"

**Severity**
Major

**Frequency of Occurrence**
Always

**Steps to Reproduce**
1. Use Redis server with Cluster mode enabled
2. Try to use redis-strings handler
3. Call revalidateTag
4. Notice how revalidateTag throws an error

**Expected vs. Actual Behavior**
I was execting that the package has support also for Redis cluster mode

**Environment:**

- OS: [e.g., MacOS, Windows, Linux]
- Node.js version: 18.20.2
- `@neshca/cache-handler` version: 1.4.0
- `next` version: 14.0.3

**Attempted Solutions or Workarounds**
keyPrefix="{myOwnPrefix}" can be used  to force key slots to be same

**Impact of the Bug**
Cannot use Redis cluster mode to it's full extend

**Comment by mauroaccornero** [comment]
I doubt you can use the redis-string handler with cluster because it accepts a client while in the node-redis's library, there's a specific method to [createCluster()](https://github.com/redis/node-redis/blob/master/docs/clustering.md). At the moment looks like a [cluster has some problem dispatching a ready event](https://github.com/redis/node-redis/issues/1855) so the client.isReady in redis-string will throw an error.  But it's possible to define a custom handler using createCluster and properly handling the keyPrefix as you mentioned. I tried [a little solution with the createCluster method](https://github.com/mauroaccornero/cache-handler-redis-cluster-example). I hope this will help you.

**Comment by better-salmon** [comment]
@Jon1VK hello! I've released version [1.5.0](https://github.com/caching-tools/next-shared-cache/releases/tag/%40neshca%2Fcache-handler%401.5.0) featuring [`experimental-redis-cluster` Handler](https://caching-tools.github.io/next-shared-cache/handlers/experimental-redis-cluster). I consider this issue fixed by PR #660.

It marked it as experimental because it lacks checks on whether the cluster is ready and automated tests.

---

@mauroaccornero thank you for your effort and creating [clustering example](https://github.com/mauroaccornero/cache-handler-redis-cluster-example).
